# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-09-01 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20180824_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
