# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-09-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20180901_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
