# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-09-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20180905_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=180),
        ),
    ]
