# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20180906_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='season',
            field=models.CharField(max_length=255),
        ),
    ]
