# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-09-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20180902_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='MM/DD/YYYY', null=True),
        ),
    ]
