# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20190306_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=180),
        ),
    ]
